version: '3.9'
services:
  node:
    image: adbarclay92/fec-barclay-trimarchi
    container_name: fec-barclay-trimarchi
    ports:
      - 1234:3000
    build:
      context: ../
      dockerfile: ./scripts/node.Dockerfile